name: Run website-stalker

on:
  push:
  schedule:
    - cron:  '17 * * * *' # every hour at minute 17

jobs:
  website-stalker:
    runs-on: ubuntu-latest
    container: ghcr.io/edjopato/website-stalker:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: run website-stalker and push
        shell: bash --noprofile --norc {0}
        run: |
          website-stalker run --all --commit
          exitcode=$?

          echo "::group::git push"
          git push
          echo "::endgroup::"

          exit $exitcode
