name: Run website-stalker

on:
  push:
  schedule:
    - cron:  '17 */2 * * *' # every two hours at minute 17

jobs:
  website-stalker:
    runs-on: ubuntu-latest
    steps:
      - name: install website-stalker
        run: |
          wget -q -O - https://github.com/EdJoPaTo/website-stalker/releases/download/v0.12.0/website-stalker-v0.12.0-x86_64-unknown-linux-gnu.tar.gz | tar xz website-stalker
          ls -al
          mv website-stalker /usr/local/bin

      - uses: actions/checkout@v2

      - name: Run website-stalker
        uses: docker://ghcr.io/edjopato/website-stalker:latest
        with:
          args: run --all --commit

      - if: always()
        run: git push
