name: website-stalker-edge

on:
  push:
  schedule:
    - cron:  '17 */6 * * *' # every six hours at minute 17

jobs:
  website-stalker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: edge

      - name: Run website-stalker
        uses: docker://ghcr.io/edjopato/website-stalker:edge
        with:
          args: run --all --commit

      - if: always()
        run: git push
