name: website-stalker

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '7 * * * *' # once per hour at minute 7

permissions:
  contents: write

jobs:
  website-stalker:
    runs-on: ubuntu-latest
    env:
      WEBSITE_STALKER_FROM: ${{ secrets.WEBSITE_STALKER_FROM }}
    steps:
      - uses: EdJoPaTo/website-stalker-github-action@v1

      - uses: actions/checkout@v4

      - name: Check website-stalker config
        run: website-stalker check

      - run: 'false'

      - name: Run website-stalker
        id: website-stalker
        run: website-stalker run --all --commit

      - if: always()
        run: echo '${{ toJSON(steps.website-stalker) }}' | jq

      - if: success() || steps.website-stalker.outcome == 'failure'
        run: git push
